In [1]:
from datetime import datetime

def convert_to_relative_time(log_lines):
    reference_time = datetime.strptime(log_lines[0][:17], '%y/%m/%d %H:%M:%S')
    relative_times = []
    for line in log_lines:
        current_time = datetime.strptime(line[:17], '%y/%m/%d %H:%M:%S')
        relative_seconds = int((current_time - reference_time).total_seconds())
        relative_time_entry = f"{relative_seconds}:{line[18:]}"
        relative_times.append(relative_time_entry)
    return relative_times


In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/svm_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['svm nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'svm nominal Count'] = value


svm_nominal_list = df['svm nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/svm_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['svm sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'svm sprinting Count'] = value

svm_sprinting_list = df['svm sprinting Count'].to_list()


In [4]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/pr_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

print(count_sec)
max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['page rank nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'page rank nominal Count'] = value


pr_nominal_list = df['page rank nominal Count'].to_list()

print(pr_nominal_list)

file_path = '/Users/jingyiwu/Documents/Project/executorLog/pr_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['page rank sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'page rank sprinting Count'] = value

pr_sprinting_list = df['page rank sprinting Count'].to_list()


{'0': 1, '1': 1, '2': 1, '22': 2, '24': 1, '43': 1, '44': 1, '45': 1, '65': 2, '66': 1, '86': 2, '88': 1, '107': 2, '109': 1, '128': 1, '129': 1, '130': 1, '149': 2, '150': 1, '168': 1, '169': 1, '170': 1, '188': 1, '189': 1, '190': 1, '208': 2, '210': 1, '228': 2, '230': 1, '248': 2, '250': 1, '268': 2, '270': 1, '288': 2, '290': 1, '308': 2, '310': 1, '328': 2, '330': 1, '348': 2, '350': 1, '368': 2, '370': 1, '387': 1, '388': 1, '390': 1, '407': 1, '408': 1, '410': 1, '428': 2, '430': 1, '447': 1, '448': 1, '450': 1, '467': 1, '469': 1, '470': 1, '487': 1, '489': 1, '490': 1, '507': 1, '508': 1, '509': 1, '527': 1, '528': 1, '529': 1, '547': 1, '548': 1, '549': 1, '567': 1, '568': 1, '569': 1, '586': 1, '588': 1, '589': 1, '606': 1, '608': 1, '609': 1, '626': 1, '628': 1, '629': 1, '646': 1, '648': 1, '649': 1, '666': 1, '668': 2, '686': 1, '687': 1, '688': 1, '706': 1, '707': 1, '708': 1, '726': 1, '727': 1, '728': 1, '746': 1, '747': 2, '766': 1, '767': 2, '786': 1, '787': 2, '806

In [5]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/lr_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['linearReg nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'linearReg nominal Count'] = value

lr_nominal_list = df['linearReg nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/lr_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['linearReg sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'linearReg sprinting Count'] = value

lr_sprinting_list = df['linearReg sprinting Count'].to_list()


In [6]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/kmeans_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['kmeans nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'kmeans nominal Count'] = value


kmeans_nominal_list = df['kmeans nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/kmeans_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)


for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['kmeans sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'kmeans sprinting Count'] = value

kmeans_sprinting_list = df['kmeans sprinting Count'].to_list()


In [7]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/als_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['als nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'als nominal Count'] = value


als_nominal_list = df['als nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/als_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['als sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'als sprinting Count'] = value

als_sprinting_list = df['als sprinting Count'].to_list()


In [8]:
def interpolation(list, target_length):
    # Original indices (0 to 5 for 6 elements)
    original_indices = np.linspace(0, len(list) - 1, num=len(list))

    # New indices for target list
    new_indices = np.linspace(0, len(list) - 1, num=target_length)

    # Interpolating to get the new list
    new_list = np.interp(new_indices, original_indices, list)

    return new_list.tolist()


In [9]:
als_sprinting_list = interpolation(als_sprinting_list, len(als_nominal_list))
kmeans_sprinting_list = interpolation(kmeans_sprinting_list, len(kmeans_nominal_list))
lr_sprinting_list = interpolation(lr_sprinting_list, len(lr_nominal_list))
pr_sprinting_list = interpolation(pr_sprinting_list, len(pr_nominal_list))
svm_sprinting_list = interpolation(svm_sprinting_list, len(svm_nominal_list))

In [10]:
l = {"als_nominal_list": als_nominal_list,
     "als_sprinting_list": als_sprinting_list,
     "kmeans_nominal_list": kmeans_nominal_list, 
     "kmeans_sprinting_list": kmeans_sprinting_list,
     "lr_nominal_list": lr_nominal_list, 
     "lr_sprinting_list": lr_sprinting_list,
     "pr_nominal_list": pr_nominal_list, 
     "pr_sprinting_list": pr_sprinting_list,
     "svm_nominal_list": svm_nominal_list, 
     "svm_sprinting_list": svm_sprinting_list}

In [11]:

with open('executorLog_list.txt', 'a+') as file:
    for item in l:
        file.write(f"{item}: {l[item]}\n")


In [12]:
import numpy as np

In [13]:
a = np.array([2,7,2,5,6,7,3,6,2,1,10, 12, 14, 15, 0, 0, 0])
np.histogram(a, np.arange(0, a.max()+2, 1))[0] / np.histogram(a, np.arange(0, a.max()+2, 1))[0].sum()

array([0.17647059, 0.05882353, 0.17647059, 0.05882353, 0.        ,
       0.05882353, 0.11764706, 0.11764706, 0.        , 0.        ,
       0.05882353, 0.        , 0.05882353, 0.        , 0.05882353,
       0.05882353])

In [14]:
a = np.array([2,7,2,5,6,7,3,6,2,1,10, 12, 14, 15, 0, 0, 0])
np.histogram(a, np.arange(0, a.max()+1, 1))[0] / np.histogram(a, np.arange(0, a.max()+1, 1))[0].sum()

array([0.17647059, 0.05882353, 0.17647059, 0.05882353, 0.        ,
       0.05882353, 0.11764706, 0.11764706, 0.        , 0.        ,
       0.05882353, 0.        , 0.05882353, 0.        , 0.11764706])

In [15]:
a = np.array([2,7,2,5,6,7,3,6,2,1,10, 12, 14, 15, 0, 0, 0])
np.histogram(a, np.arange(0, a.max()+3, 1))[0] / np.histogram(a, np.arange(0, a.max()+3, 1))[0].sum()

array([0.17647059, 0.05882353, 0.17647059, 0.05882353, 0.        ,
       0.05882353, 0.11764706, 0.11764706, 0.        , 0.        ,
       0.05882353, 0.        , 0.05882353, 0.        , 0.05882353,
       0.05882353, 0.        ])

In [16]:
np.histogram(a, np.arange(0, a.max()+1, 1))[0]

array([3, 1, 3, 1, 0, 1, 2, 2, 0, 0, 1, 0, 1, 0, 2])

In [17]:
np.arange(a.min(), a.max()+1) / a.max()

array([0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
       0.33333333, 0.4       , 0.46666667, 0.53333333, 0.6       ,
       0.66666667, 0.73333333, 0.8       , 0.86666667, 0.93333333,
       1.        ])