In [1]:
from datetime import datetime

def convert_to_relative_time(log_lines):
    reference_time = datetime.strptime(log_lines[0][:17], '%y/%m/%d %H:%M:%S')
    relative_times = []
    for line in log_lines:
        current_time = datetime.strptime(line[:17], '%y/%m/%d %H:%M:%S')
        relative_seconds = int((current_time - reference_time).total_seconds())
        relative_time_entry = f"{relative_seconds}:{line[18:]}"
        relative_times.append(relative_time_entry)
    return relative_times


In [2]:
import pandas as pd
import numpy as np

In [3]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/svm_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['svm nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'svm nominal Count'] = value


svm_nominal_list = df['svm nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/svm_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['svm sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'svm sprinting Count'] = value

svm_sprinting_list = df['svm sprinting Count'].to_list()


In [13]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/pr_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

print(count_sec)
max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['page rank nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'page rank nominal Count'] = value


pr_nominal_list = df['page rank nominal Count'].to_list()

print(pr_nominal_list)

file_path = '/Users/jingyiwu/Documents/Project/executorLog/pr_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['page rank sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'page rank sprinting Count'] = value

pr_sprinting_list = df['page rank sprinting Count'].to_list()


{'0': 5, '1': 5, '2': 2, '59': 3, '60': 4, '61': 4, '62': 1, '114': 1, '115': 2, '116': 4, '118': 1, '119': 2, '121': 2, '169': 1, '171': 1, '172': 4, '176': 2, '177': 2, '178': 2, '226': 1, '227': 2, '228': 1, '230': 2, '232': 2, '233': 1, '234': 1, '235': 2, '282': 1, '283': 1, '284': 1, '285': 1, '286': 1, '287': 1, '288': 1, '289': 2, '291': 1, '292': 1, '293': 1, '339': 1, '340': 1, '341': 1, '342': 1, '343': 4, '345': 1, '347': 1, '348': 1, '349': 1, '395': 1, '396': 2, '398': 2, '399': 2, '401': 1, '403': 2, '406': 1, '410': 1, '452': 2, '453': 3, '456': 3, '457': 1, '460': 1, '465': 2, '508': 2, '509': 1, '510': 2, '511': 1, '512': 1, '513': 2, '516': 1, '522': 2, '565': 3, '566': 2, '567': 1, '568': 2, '571': 1, '573': 1, '578': 1, '579': 1, '621': 1, '622': 3, '623': 2, '625': 2, '628': 1, '630': 1, '635': 2, '677': 2, '678': 2, '679': 1, '680': 3, '686': 1, '690': 1, '692': 2, '732': 1, '734': 2, '736': 2, '737': 2, '738': 1, '744': 1, '745': 1, '748': 2, '787': 1, '791': 2,

In [5]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/lr_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['linearReg nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'linearReg nominal Count'] = value

lr_nominal_list = df['linearReg nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/lr_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['linearReg sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'linearReg sprinting Count'] = value

lr_sprinting_list = df['linearReg sprinting Count'].to_list()


In [6]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/kmeans_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['kmeans nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'kmeans nominal Count'] = value


kmeans_nominal_list = df['kmeans nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/kmeans_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)


for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['kmeans sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'kmeans sprinting Count'] = value

kmeans_sprinting_list = df['kmeans sprinting Count'].to_list()


In [7]:
file_path = '/Users/jingyiwu/Documents/Project/executorLog/als_nominal_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)
df = pd.DataFrame(index=range(max_key + 1))
df['als nominal Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'als nominal Count'] = value


als_nominal_list = df['als nominal Count'].to_list()

file_path = '/Users/jingyiwu/Documents/Project/executorLog/als_sprinting_executorLog.txt'
log_lines = []
with open(file_path, 'r') as file:
    for line in file:
        if "Executor: !!!!Finished task" in line.strip():
            log_lines.append(line.strip()) 
count_sec = {}
relative_time_lines = convert_to_relative_time(log_lines)

for line in relative_time_lines:
    info = line.split(":", 1)
    if info[0] in count_sec:
        count_sec[info[0]] += 1
    else:
        count_sec[info[0]] = 1

max_key = max(int(key) for key in count_sec)

df = pd.DataFrame(index=range(max_key + 1))
df['als sprinting Count'] = 0

for key, value in count_sec.items():
    df.at[int(key), 'als sprinting Count'] = value

als_sprinting_list = df['als sprinting Count'].to_list()


In [8]:
def interpolation(list, target_length):
    # Original indices (0 to 5 for 6 elements)
    original_indices = np.linspace(0, len(list) - 1, num=len(list))

    # New indices for target list
    new_indices = np.linspace(0, len(list) - 1, num=target_length)

    # Interpolating to get the new list
    new_list = np.interp(new_indices, original_indices, list)

    return new_list.tolist()


In [9]:
als_sprinting_list = interpolation(als_sprinting_list, len(als_nominal_list))
kmeans_sprinting_list = interpolation(kmeans_sprinting_list, len(kmeans_nominal_list))
lr_sprinting_list = interpolation(lr_sprinting_list, len(lr_nominal_list))
pr_sprinting_list = interpolation(pr_sprinting_list, len(pr_nominal_list))
svm_sprinting_list = interpolation(svm_sprinting_list, len(svm_nominal_list))

In [10]:
l = {"als_nominal_list": als_nominal_list,
     "als_sprinting_list": als_sprinting_list,
     "kmeans_nominal_list": kmeans_nominal_list, 
     "kmeans_sprinting_list": kmeans_sprinting_list,
     "lr_nominal_list": lr_nominal_list, 
     "lr_sprinting_list": lr_sprinting_list,
     "pr_nominal_list": pr_nominal_list, 
     "pr_sprinting_list": pr_sprinting_list,
     "svm_nominal_list": svm_nominal_list, 
     "svm_sprinting_list": svm_sprinting_list}

In [11]:

with open('executorLog_list.txt', 'a+') as file:
    for item in l:
        file.write(f"{item}: {l[item]}\n")


In [1]:
import numpy as np

In [31]:
a = np.array([2,7,2,5,6,7,3,6,2,1,10, 12, 14, 15, 0, 0, 0])
np.histogram(a, np.arange(0, a.max()+2, 1))[0] / np.histogram(a, np.arange(0, a.max()+2, 1))[0].sum()

array([0.17647059, 0.05882353, 0.17647059, 0.05882353, 0.        ,
       0.05882353, 0.11764706, 0.11764706, 0.        , 0.        ,
       0.05882353, 0.        , 0.05882353, 0.        , 0.05882353,
       0.05882353])

In [32]:
a = np.array([2,7,2,5,6,7,3,6,2,1,10, 12, 14, 15, 0, 0, 0])
np.histogram(a, np.arange(0, a.max()+1, 1))[0] / np.histogram(a, np.arange(0, a.max()+1, 1))[0].sum()

array([0.17647059, 0.05882353, 0.17647059, 0.05882353, 0.        ,
       0.05882353, 0.11764706, 0.11764706, 0.        , 0.        ,
       0.05882353, 0.        , 0.05882353, 0.        , 0.11764706])

In [33]:
a = np.array([2,7,2,5,6,7,3,6,2,1,10, 12, 14, 15, 0, 0, 0])
np.histogram(a, np.arange(0, a.max()+3, 1))[0] / np.histogram(a, np.arange(0, a.max()+3, 1))[0].sum()

array([0.17647059, 0.05882353, 0.17647059, 0.05882353, 0.        ,
       0.05882353, 0.11764706, 0.11764706, 0.        , 0.        ,
       0.05882353, 0.        , 0.05882353, 0.        , 0.05882353,
       0.05882353, 0.        ])

In [25]:
np.histogram(a, np.arange(0, a.max()+1, 1))[0]

array([3, 1, 3, 1, 0, 1, 2, 2, 0, 0, 1, 0, 1, 0, 2])

In [28]:
np.arange(a.min(), a.max()+1) / a.max()

array([0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
       0.33333333, 0.4       , 0.46666667, 0.53333333, 0.6       ,
       0.66666667, 0.73333333, 0.8       , 0.86666667, 0.93333333,
       1.        ])